"""Declarative NPU operator IR, legal tiling solver and cycle simulator."""

from .hardware import Hardware, ResourceRate, ascend_910b3
from .cann_matmul import (
    CANN81_MATMUL_FAMILIES,
    CANN81_MATMUL_KERNEL_SUFFIXES,
    FixOptMode,
    FullLoadMode,
    MatmulExecutionGraph,
    SplitCoreMode,
    base_plan_from_cann,
    cann81_matmul_effective_l1_bytes,
    decode_execution_graph,
    execution_mode_name,
    kernel_suffix,
    source_kernel_suffix,
    lower_plan_to_cann,
    plan_from_cann,
    simulate_cann_base,
    validate_cann_tiling,
)
from .ir import (
    Access,
    AccessMode,
    AccessPattern,
    Algorithm,
    Axis,
    AxisKind,
    MemorySpace,
    Operator,
    Primitive,
    ReductionProtocol,
    Resource,
    Stage,
    StageScope,
    Tensor,
    TileLevel,
    WorkspaceBuffer,
    WorkspaceDimension,
)
from .schedule import (
    IdealRegion,
    RankedTiling,
    ScheduleSpace,
    SearchPolicy,
    SolveResult,
    TilingPlan,
)
from .simulator import SimulationResult, simulate
from .solver import (
    derive_ideal_region,
    generate_plans,
    plan_space_size,
    solve,
    solve_ideal_region,
)

__all__ = [
    "Access",
    "AccessMode",
    "AccessPattern",
    "Algorithm",
    "Axis",
    "AxisKind",
    "CANN81_MATMUL_FAMILIES",
    "CANN81_MATMUL_KERNEL_SUFFIXES",
    "Hardware",
    "IdealRegion",
    "MemorySpace",
    "MatmulExecutionGraph",
    "Operator",
    "Primitive",
    "ReductionProtocol",
    "RankedTiling",
    "Resource",
    "ResourceRate",
    "SplitCoreMode",
    "FullLoadMode",
    "FixOptMode",
    "ScheduleSpace",
    "SearchPolicy",
    "SimulationResult",
    "SolveResult",
    "Stage",
    "StageScope",
    "Tensor",
    "TileLevel",
    "WorkspaceBuffer",
    "WorkspaceDimension",
    "TilingPlan",
    "ascend_910b3",
    "base_plan_from_cann",
    "cann81_matmul_effective_l1_bytes",
    "derive_ideal_region",
    "decode_execution_graph",
    "execution_mode_name",
    "kernel_suffix",
    "source_kernel_suffix",
    "lower_plan_to_cann",
    "plan_from_cann",
    "generate_plans",
    "plan_space_size",
    "simulate",
    "simulate_cann_base",
    "validate_cann_tiling",
    "solve",
    "solve_ideal_region",
]
